### ISSUE TITLE
New linter: oe_structure element without specific id

### ISSUE THREAD

**Issue by yajo** [OCA/odoo-pre-commit-hooks#27]
Odoo website builder will replace a view if it contains something like this and the user edits that section:

```xml
<div class="oe_structure"/>
```

However, since Odoo v12, if it is in this other format, instead of creating a COW view that completely replaces the previous one, [it will create an extension view that replaces this specific element in the parent view](https://github.com/odoo/odoo/blob/25edcc89273c389f318c434ce9a9e0b531b8e599/addons/web_editor/models/ir_ui_view.py#L41):

```xml
<div id="oe_structure_SOME_HOOK_HERE" class="oe_structure"/>
```

This provides a more resilient upgrade path because your module can "safely"\* update the base view which contains logic, while user customizations are kept separately.

IMHO this is a good candidate for a linter.

---

\* You know that in Odoo nothing is exactly "safe", but it's better. :shrug:

**Comment by antonag32** [comment]
Hello @yajo 

Just to verify about the behavior you intended:

1. Should this lint only apply to elements with no children?
2. Should the id for this elements always start with `oe_structure`?

**Comment by luisg123v** [comment]
> Should the id for this elements always start with oe_structure?

Maybe not mandatory, but it's a good idea to follow Odoo's way:

`oe_structure_<template_id>_<some_unique_id>`

(suggestion taken from @imanie383).

Whether it's mandatory or not, if we agree on a specific format, it should be mentioned in the error message.

I'll reopen this issue to address mentioned points.

**Comment by antonag32** [comment]
Also, is using `t-attf-id` valid? Or must it be `id`? :thinking:

**Comment by imanie383** [comment]
> Also, is using `t-attf-id` valid? Or must it be `id`? thinking

![image](https://github.com/OCA/odoo-pre-commit-hooks/assets/35231827/f9266a57-46f8-4c83-9625-119c76997701)


https://github.com/odoo/odoo/blob/25edcc89273c389f318c434ce9a9e0b531b8e599/addons/web_editor/models/ir_ui_view.py#L41

**Comment by antonag32** [comment]
> > Also, is using `t-attf-id` valid? Or must it be `id`? thinking
> 
> ![image](https://user-images.githubusercontent.com/35231827/251630852-f9266a57-46f8-4c83-9625-119c76997701.png)
> 
> https://github.com/odoo/odoo/blob/25edcc89273c389f318c434ce9a9e0b531b8e599/addons/web_editor/models/ir_ui_view.py#L41

Thanks, that confirms my suspicion. The lint will now ensures all ids contain `oe_structure`.  However I am still not sure about `t-attf-id`. Is `t-attf-id` converted to `id` before the xpath evaluation?

Is this valid, or should the linter complain?
```
<div class="oe_structure" t-attf-id="oe_structure_blog_single_header_#{blog.id}" />
```

Also, should we ignore the following special case (anything with id="wrap")?

```
div class="oe_structure" id="wrap"
```

**Comment by yajo** [comment]
> Is this valid, or should the linter complain?
> 
> ```
> <div class="oe_structure" t-attf-id="oe_structure_blog_single_header_#{blog.id}" />
> ```

This should make the linter fail anyway because it's a `div` with class `oe_structure` and without `oe_structure` in its `id` (because `t-attf-id` isn't enough).

However, that's an invalid example and it makes no sense.

The use case for this is to have a customizable _static_ section in a qweb view.

If you want to have a section customizable _per record_ (not statically), it is better to add a field to the model and just expose it as an HTML-editable `t-field`. Your example would become:

```html
<div t-field="blog.header"/>
```



> Also, should we ignore the following special case (anything with id="wrap")?
>
> ```
> div class="oe_structure" id="wrap"
> ```

This one is also not realistic.

If you made such a template, you'd be basically creating an empty page. It makes no sense to do so, because Odoo can already do that by just clicking on add page, so why would you create a module with an empty page?

Even if it had any sense, you could easily solve the problem with:

```html
<div id="wrap">
  <div class="oe_structure" id="oe_structure_body"/>
</div>
```

... or you could deactivate the linter inline, just like usual (because we can do that, right? 🤔).

**Comment by moylop260** [comment]
Second part from https://github.com/OCA/odoo-pre-commit-hooks/pull/81
