### ISSUE TITLE
duplicate-xml-record-id should also apply to template and probably others

### ISSUE THREAD

**Issue by hbrunn** [OCA/odoo-pre-commit-hooks#28]
in https://github.com/OCA/pylint-odoo/blob/master/pylint_odoo/checkers/modules_odoo.py#L499 we check if one record overwrites another. This function only operates on `record` nodes, while we have a bunch of other nodes like `template` which also create records and possibly overwrite each other.

I think we should add some other helper function that yields all record creating nodes and use that in this function, right?

**Comment by moylop260** [comment]
@hbrunn 

Odoo now supports duplicated fields in xml views:
 - https://github.com/odoo/odoo/pull/103743

I remember that it was an error in the past for backend views

Could you double-confirm if your issue is still valid for templates?

I mean, what happen if there are duplicated fields?

Regards!

**Comment by hbrunn** [comment]
still valid I think, as the overwriting check is meant for doing inheritance wrongly, isn't it?
