### ISSUE TITLE
Forbid usage of qweb.add_template(), use ajax.loadXML()

### ISSUE THREAD

**Issue by yajo** [OCA/odoo-pre-commit-hooks#31]
Hi there linter pros! This issue and specifically this comment is what I'm referring to: https://github.com/odoo/odoo/issues/20821#issuecomment-358577401

Summarizing, there's the common pattern (also used by Odoo itself) of synchronously loading client-side xml qweb templates by using `qweb.add_template('/addon/static/xml/sometemplate.xml')`, but the correct way of doing this would be by using `ajax.loadXML('addon/static/xml/sometemplate.xml', core.qweb)`.

The difference is that it is being loaded synchronously with the 1st method, and asynchronously with the 2nd. So, the 2nd makes the whole website more responsive, and returns a `$.Deferred()` that can be chained to avoid race conditions.

Example fix of one of these problems: https://github.com/odoo/odoo/pull/22330

Having a linter that forbids using that method would be just freaking awesome!

**Comment by moylop260** [comment]
@yajo 

I just moved from pylint-odoo to odoo-pre-commit-hooks this issue since it is not a python checker request


In fact, it is a JS checker but we don't have developed a checker for this extension of files

Could you check if eslint parameter allow us to configure deprecated methods?

**Comment by yajo** [comment]
I have no idea. However, it's for detecting a change that was done in a version that is very old. If we survived all this time, I guess this can be just closed. Reopen otherwise 😄 

Thanks for keeping the house clean!
