### ISSUE TITLE
Add configparser for message control

### ISSUE THREAD

**Issue by moylop260** [OCA/odoo-pre-commit-hooks#37]
Add a configuration file by default `$(pwd)/.oca_pch.cfg` if not then `~/.oca_pch.cfg` but prefer the parameter `-c --config`

Notice the name is only an idea since it is hard to me the named of things

```config
[MESSAGES CONTROL]  # Name inspired in .pylintrc
enable=check-name_x,
    check-name_y,

disable=check-name_z,
    check-name_w,
```

Using the built-in python lib `configparser` in order to avoid adding new requirements

**Comment by antonag32** [comment]
For the record, after talking with some other devs, `.oca_hooks.cfg` was chosen.

**Comment by moylop260** [comment]
As part of this same issue

Could you add in the README and example of the configuration file with options, please?

**Comment by moylop260** [comment]
Add default values in the argument parser related to argument config:
 - `--config CONFIG, -c CONFIG Path to a configuration file`

See example from `doc8 --help`

```txt
  --config path         user config file location (default: doc8.ini, .config/doc8.ini,
                        tox.ini, pep8.ini, setup.cfg, pyproject.toml).
```
