### ISSUE TITLE
[BUG] oca-hooks:disable doesn't ingore the selected check

### ISSUE THREAD

**Issue by AungKoKoLin1997** [OCA/odoo-pre-commit-hooks#88]
Hi, firstly thanks for this tool.
I want to disable `xml-view-dangerous-replace-low-priority` for my xml file. 
So, I defined like this in my xml file.
```
<?xml version="1.0" encoding="utf-8" ?>
<!-- oca-hooks:disable=xml-view-dangerous-replace-low-priority -->
<odoo>
  ...
</odoo>
```
Then, when I run the pre-commit,  this check is not ingored and I still got the warning.

```
Checks for Odoo modules..................................................Failed
- hook id: oca-checks-odoo-module
- exit code: 1

****xml-view-dangerous-replace-low-priority****
my_module/views/my_custom_views.xml:4 Dangerous use of "replace" from view with priority 0 < 99. Only replace as a last resort. Try position="attributes", position="move" or invisible="1" first - [xml-view-dangerous-replace-low-priority]
my_module/views/my_custom_views.xml:37 Dangerous use of "replace" from view with priority 0 < 99. Only replace as a last resort. Try position="attributes", position="move" or invisible="1" first - [xml-view-dangerous-replace-low-priority]
```

@qrtl

**Comment by antonag32** [comment]
Hello @AungKoKoLin1997, can you provide more information, for example the package's version and your pre-commit configuration? If your repository is public and you could share it that would be ideal.

I tried to reproduce but I can't. I tried the following:

```bash
git clone https://github.com/OCA/odoo-pre-commit-hooks.git
cd odoo-pre-commit-hooks
oca-checks-odoo-module test_repo/broken_module/model_view2.xml --enable=xml-view-dangerous-replace-low-priority
```

The referenced file is this one: https://github.com/OCA/odoo-pre-commit-hooks/blob/5e97e13778f2cf7440bc711171f9e4db69a0f6a7/test_repo/broken_module/model_view2.xml

After adding `<!-- oca-hooks:disable=xml-view-dangerous-replace-low-priority -->` to the file (as in your example) I no longer  get any `xml-view-dangerous-replace-low-priority` messages.

**Comment by AungKoKoLin1997** [comment]
@antonag32 Thanks for your response. 
Actually, I was trying to update my existing dotfiles to reflect the latest changes from `oca-addons-repo-template`. So, I tried to update using `copier update` and I adjusted some disable check in my modules. This is my PR for updating dotfiles https://github.com/qrtl/rmm-custom/pull/69. I hope this information help you.

**Comment by antonag32** [comment]
@AungKoKoLin1997 

Thanks, that helps. I reviewed your config file and the CI, it seems like the message is actually being generated by pylint and not oca-hooks. Previously pylint implemented functionality which was moved into these hooks.

Try changing the pylint version in `.pre-commit-config.yaml` from 7.0.2 to something like 8.0.22, that should fix your issue. From version 8 and onwards pylint checks only python files, and all checks for XML, CSV and PO files were moved to this repository.

You may also want to update your hooks version from v0.0.25 to v0.0.29 (the latest).

Let me know if that works.

**Comment by AungKoKoLin1997** [comment]
@antonag32 
Thanks for your help.
Changing pylint version doesn't solve the issue and lead to the errors.
```
[INFO] Initializing environment for https://github.com/OCA/pylint-odoo.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', '8.0.22')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec '8.0.22' did not match any file(s) known to git
```
So, I tried to change hooks version. It worked but `oca-checks-po` raises 'not formatted correctly' for most of my modules. Actually, I export the po file from odoo language export and add some translation. This doesn't happen when hooks was v0.0.25. So, I disable this check at the moment https://github.com/qrtl/rmm-custom/pull/69/commits/81e23a2e6fc66c4a248a75a565d3caa151ade2f5. The pain is there is no clue about which line in po file causes ugly format. I will be happy if you have any suggestion.

**Comment by antonag32** [comment]
Sorry, I should mention the pylint version needs a 'v' before the number. It should be `rev: v8.0.22` for example. Basically any valid tag: https://github.com/OCA/pylint-odoo/tags

Please try again with a correct tag revision. 

As for the po format, there is an autofix option. You could run it and pass the `--fix` argument to it. It will fix all your files automatically, so that should get rid of that error.

At Vauxoo we use these hooks and pylint. You may benefit from reading the configuration we use for pre-commit:

https://github.com/Vauxoo/pre-commit-vauxoo/blob/be1f1f39e024d41d40d76ca4f901ba63583d79fb/src/pre_commit_vauxoo/cfg/.pre-commit-config-autofix.yaml

https://github.com/Vauxoo/pre-commit-vauxoo/blob/be1f1f39e024d41d40d76ca4f901ba63583d79fb/src/pre_commit_vauxoo/cfg/.pre-commit-config-optional.yaml

**Comment by AungKoKoLin1997** [comment]
I just realized whatever we change versions, the issue is still exist if we don't add `<field name="priority" eval="100" />` in view's definition.
This is the log for hooks: v0.0.25 and pylint: 7.0.2. The result is the same with or without `<!-- oca-hooks:disable=xml-view-dangerous-replace-low-priority --> ` in xml.
![Screenshot from 2023-10-05 10-59-12](https://github.com/OCA/odoo-pre-commit-hooks/assets/45355704/6191b706-bb79-441b-bff6-334c95b40e38)

This is the log after changing hooks: v0.0.29 without adding `<field name="priority" eval="100" />`
![Screenshot from 2023-10-05 11-09-17](https://github.com/OCA/odoo-pre-commit-hooks/assets/45355704/65cf03c8-21cd-4f47-8cb0-3d99f6b74774)

This is the log after changing pylint: v8.0.22 with hooks: v0.0.25. This is worse. Even I only added my company for `manifest_required_authors` in `.pylintrc` and `.pylintrc-mandatory`, OCA authored is still checked.


![Screenshot from 2023-10-05 11-10-57](https://github.com/OCA/odoo-pre-commit-hooks/assets/45355704/e5a53c42-f6e2-40be-b153-008a3b33e039)

**Comment by moylop260** [comment]
@AungKoKoLin1997 

Could you share a PR with minimal changes to reproduce the last comment, please?

**Comment by AungKoKoLin1997** [comment]
@moylop260 
This is my PR https://github.com/qrtl/rmm-custom/pull/69.

**Comment by AungKoKoLin1997** [comment]
@moylop260  Thanks for your help.

> The PR you shared is not reproducing the issue that you are sharing in the images

As I explained in my comment, I tried with multiple version. 
All of the images are generated by running in my local environment and the result will be the same in PR.
My PR is the same result with the second image of my comment.
I can't reproduce all of my images in one PR because I tested with multiple versions.

**Comment by AungKoKoLin1997** [comment]
I created new PR with minimal changes https://github.com/qrtl/rmm-custom/pull/70/files

**Comment by moylop260** [comment]
@AungKoKoLin1997 

Thank you for your PR now I can identify the problems easiest

You need to apply the following patches:

1) Upgrade latest pylint-odoo version
2) Use the new parameter style for new pylint-odoo version

```diff
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index cac4934..7f1add4 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -139,7 +139,7 @@ repos:
         name: flake8
         additional_dependencies: ["flake8-bugbear==21.9.2"]
   - repo: https://github.com/OCA/pylint-odoo
-    rev: 7.0.2
+    rev: v8.0.22
     hooks:
       - id: pylint_odoo
         name: pylint with optional checks
diff --git a/.pylintrc b/.pylintrc
index b8e688d..a0a0547 100644
--- a/.pylintrc
+++ b/.pylintrc
@@ -5,12 +5,12 @@ load-plugins=pylint_odoo
 score=n
 
 [ODOOLINT]
-readme_template_url="https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst"
-manifest_required_authors=Quartile Limited
-manifest_required_keys=license
-manifest_deprecated_keys=description,active
-license_allowed=AGPL-3,GPL-2,GPL-2 or any later version,GPL-3,GPL-3 or any later version,LGPL-3
-valid_odoo_versions=15.0
+readme-template-url="https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst"
+manifest-required-authors=Quartile Limited
+manifest-required-keys=license
+manifest-deprecated-keys=description,active
+license-allowed=AGPL-3,GPL-2,GPL-2 or any later version,GPL-3,GPL-3 or any later version,LGPL-3
+valid-odoo-versions=15.0
 
 [MESSAGES CONTROL]
 disable=all
diff --git a/.pylintrc-mandatory b/.pylintrc-mandatory
index 998b81d..5e41649 100644
--- a/.pylintrc-mandatory
+++ b/.pylintrc-mandatory
@@ -4,12 +4,12 @@ load-plugins=pylint_odoo
 score=n
 
 [ODOOLINT]
-readme_template_url="https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst"
-manifest_required_authors=Quartile Limited
-manifest_required_keys=license
-manifest_deprecated_keys=description,active
-license_allowed=AGPL-3,GPL-2,GPL-2 or any later version,GPL-3,GPL-3 or any later version,LGPL-3
-valid_odoo_versions=15.0
+readme-template-url="https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst"
+manifest-required-authors=Quartile Limited
+manifest-required-keys=license
+manifest-deprecated-keys=description,active
+license-allowed=AGPL-3,GPL-2,GPL-2 or any later version,GPL-3,GPL-3 or any later version,LGPL-3
+valid-odoo-versions=15.0
 
 [MESSAGES CONTROL]
 disable=all
```

After that the result is:
 - <img width="936" alt="Screenshot 2023-10-05 at 10 13 16 a m" src="https://github.com/OCA/odoo-pre-commit-hooks/assets/6644187/bb0e7ace-d78e-41ee-95f0-fdf5a20c058d">

**Comment by AungKoKoLin1997** [comment]
@moylop260 I really appreciate your help.
