### ISSUE TITLE
Mechanism to explicitly select enabled checks

### ISSUE THREAD

**Issue by sbidoul** [OCA/odoo-pre-commit-hooks#9]
For OCA, it is better to have a mechanism to explicitly select checks that are enabled.
This way we enable new checks when creating new branches.
And we can still upgrade the tool to get bug fixes on older branches without breaking CI due to new checks.

**Comment by moylop260** [comment]
Hi @sbidoul 

Thank you for the issue

I have added the "enable" feature

I still need to update the README but you can see it in the following unittests:
 - https://github.com/OCA/odoo-pre-commit-hooks/blob/7b907d98b573ba/tests/test_checks.py#L187

**Comment by moylop260** [comment]
@sbidoul 

Let me know if it is enough or if we need to do something else here

**Comment by sbidoul** [comment]
Looks good yes, thanks!
