### ISSUE TITLE
Is it false positive of po-duplicate-message-definition message?

### ISSUE THREAD

**Issue by voronind** [OCA/odoo-pre-commit-hooks#92]
Why this example is not false positive?
https://github.com/OCA/odoo-pre-commit-hooks/blob/v0.0.29/test_repo/broken_module/i18n/es.po#L65

We translates messages with different xml ids. This messages has different translated msgstr.

How we must translate terms with many values (i.e. key, body)?

**Comment by pedrobaeza** [comment]
It's totally correct to report that as incorrect. PO files by definition shouldn't have duplicated msgid. For the example you put, the correct way to put it is:

```
#. module: broken_module
#: model:ir.model.fields,field_description5:broken_module.field_wizard_description5
#: model:ir.model.fields,field_description10:broken_module.field_wizard_description10
#, python-format
msgid "One variable {variable1}"
msgstr "Translated 2 {variable1} {variable2}"
```

Closing as answered.

**Comment by voronind** [comment]
@moylop260 
We have 2 models. In many languages translations for this two terms will be different. How do right po files for that?

```python
class KeyboardKey(models.Model):
    _name = 'keyboard.key'

    key = fields.Char(string='Key')

class LockKey(models.Model):
    _name = 'lock.key'

    key = fields.Char(string='Key')
```

**Comment by voronind** [comment]
PO format supports ambiguous terms with context specifier (msgctxt) that's why msgfmt report error.
Odoo uses PO entitie's reference value to translate same terms.

I created `test_trans` module with model.
```python
class TestTranslate(models.Model):
    _name = 'test.translate'

    field_1 = fields.Char('Field')
    field_2 = fields.Char('Field')
```
Added to i18n file
```
#. module: test_trans
#: model:ir.model.fields,field_description:test_trans.field_test_translate_field_1
msgid "Field"
msgstr "Trans 1"

#. module: test_trans
#: model:ir.model.fields,field_description:test_trans.field_test_translate_field_2
msgid "Field"
msgstr "Trans 2"
```
Added form view with fields field_1 and field_2. Odoo shows form with "Trans 1" and "Trans 2" labels.
